package com.ictdemy.data.entities;

import jakarta.persistence.*;

/**
 * Entity representing a product in the database.
 * This class maps to the `ProductEntity` table in the database
 * and defines its fields and relationships.
 */
@Entity
public class ProductEntity {

    /**
     * The unique identifier for the product.
     * This field is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    /**
     * The name of the product.
     * Cannot be null.
     */
    @Column(nullable = false)
    private String name;

    /**
     * The description of the product.
     * Cannot be null.
     */
    @Column(nullable = false)
    private String description;

    /**
     * The price of the product.
     * Cannot be null.
     */
    @Column(nullable = false)
    private double price;

    /**
     * Gets the unique identifier for the product.
     *
     * @return the product ID.
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the unique identifier for the product.
     *
     * @param id the product ID.
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Gets the name of the product.
     *
     * @return the product name.
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the product.
     *
     * @param name the product name.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the description of the product.
     *
     * @return the product description.
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the description of the product.
     *
     * @param description the product description.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Gets the price of the product.
     *
     * @return the product price.
     */
    public double getPrice() {
        return price;
    }

    /**
     * Sets the price of the product.
     *
     * @param price the product price.
     */
    public void setPrice(double price) {
        this.price = price;
    }
}
